apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: packet-capture
  namespace: kube-system
  labels:
    app: packet-capture
spec:
  selector:
    matchLabels:
      app: packet-capture
  template:
    metadata:
      labels:
        app: packet-capture
    spec:
      hostPID: true
      serviceAccountName: packet-capture-sa
      containers:
        - name: packet-capture
          image: simple-packet-capture:latest
          imagePullPolicy: Never
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: host-proc
              mountPath: /host/proc
              readOnly: true
      volumes:
        - name: host-proc
          hostPath:
            path: /proc
